In [16]:
import numpy as np

In [17]:
l= [1,2,3,4]
arr = np.array(l)
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [18]:
a = [2,3,4,5]
np.asanyarray(a)

array([2, 3, 4, 5])

In [19]:
b = np.matrix([1,3,4,5])
print(b)

[[1 3 4 5]]


In [20]:
np.asanyarray(b)

matrix([[1, 3, 4, 5]])

In [21]:
arr.shape

(4,)

In [22]:
arr.size

4

In [23]:
a = np.array(l)
c = a 
print(c)
print(a)
c[0] = 100
print(a)
print(c)
# This is a shallow copy 


[1 2 3 4]
[1 2 3 4]
[100   2   3   4]
[100   2   3   4]


In [24]:
# deep copy 
a = np.array(l)
c = np.copy(a)
print(a)
print(c)
a [0]=400
print(a)
print(c)

[1 2 3 4]
[1 2 3 4]
[400   2   3   4]
[1 2 3 4]


In [25]:
np.fromfunction(lambda i , j : i == j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i , j : i ** j ,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [30]:
iterable = (i* i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [31]:
np.fromiter([1,2,3,4],int)

array([1, 2, 3, 4])

In [32]:
np.fromstring('1 2 3 4 ',sep=' ')

array([1., 2., 3., 4.])

In [33]:
np.fromstring('1,2,3,4,5',sep=',')

array([1., 2., 3., 4., 5.])

In [34]:
# data types in pyton
l = [2,3,4,5,6]
ar = np.array(l)
print(ar)
print(ar.ndim)

[2 3 4 5 6]
1


In [37]:
ar1 = np.array([[1,2],[3,4]])
print(ar1)
print(ar1.size)
print(ar1.shape)
print(ar1.ndim)
print(ar1.dtype)

[[1 2]
 [3 4]]
4
(2, 2)
2
int32


In [39]:
ar2 = np.array([(1.4,3,3.3),(5,43,5)])
print(ar2)

[[ 1.4  3.   3.3]
 [ 5.  43.   5. ]]


In [40]:
# using range
for i in range(4):
    print(i)

0
1
2
3


In [41]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [43]:
list(np.arange(1,23,0.25))

[1.0,
 1.25,
 1.5,
 1.75,
 2.0,
 2.25,
 2.5,
 2.75,
 3.0,
 3.25,
 3.5,
 3.75,
 4.0,
 4.25,
 4.5,
 4.75,
 5.0,
 5.25,
 5.5,
 5.75,
 6.0,
 6.25,
 6.5,
 6.75,
 7.0,
 7.25,
 7.5,
 7.75,
 8.0,
 8.25,
 8.5,
 8.75,
 9.0,
 9.25,
 9.5,
 9.75,
 10.0,
 10.25,
 10.5,
 10.75,
 11.0,
 11.25,
 11.5,
 11.75,
 12.0,
 12.25,
 12.5,
 12.75,
 13.0,
 13.25,
 13.5,
 13.75,
 14.0,
 14.25,
 14.5,
 14.75,
 15.0,
 15.25,
 15.5,
 15.75,
 16.0,
 16.25,
 16.5,
 16.75,
 17.0,
 17.25,
 17.5,
 17.75,
 18.0,
 18.25,
 18.5,
 18.75,
 19.0,
 19.25,
 19.5,
 19.75,
 20.0,
 20.25,
 20.5,
 20.75,
 21.0,
 21.25,
 21.5,
 21.75,
 22.0,
 22.25,
 22.5,
 22.75]

In [45]:
np.linspace(1,4,21)

array([1.  , 1.15, 1.3 , 1.45, 1.6 , 1.75, 1.9 , 2.05, 2.2 , 2.35, 2.5 ,
       2.65, 2.8 , 2.95, 3.1 , 3.25, 3.4 , 3.55, 3.7 , 3.85, 4.  ])

In [46]:
np.logspace(1,10,25)

array([1.00000000e+01, 2.37137371e+01, 5.62341325e+01, 1.33352143e+02,
       3.16227766e+02, 7.49894209e+02, 1.77827941e+03, 4.21696503e+03,
       1.00000000e+04, 2.37137371e+04, 5.62341325e+04, 1.33352143e+05,
       3.16227766e+05, 7.49894209e+05, 1.77827941e+06, 4.21696503e+06,
       1.00000000e+07, 2.37137371e+07, 5.62341325e+07, 1.33352143e+08,
       3.16227766e+08, 7.49894209e+08, 1.77827941e+09, 4.21696503e+09,
       1.00000000e+10])

In [47]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
ar = np.zeros((3,4))

In [50]:
ar+ 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [51]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
ar4 = np.ones((3,4,3,3))
ar4.shape
ar4.size
ar4.ndim

4

In [58]:
ar4 + 5

array([[[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]],


       [[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]],


       [[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]]])

In [59]:
ar4 - 4

array([[[[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]]],


       [[[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]]],


       [[[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]],

        [[-3., -3., -3.],
         [-3., -3., -3.],
         [-3., -3., -3.]]]])

In [60]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [61]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.random.randint(1,10,(3,3))

array([[3, 7, 6],
       [3, 7, 5],
       [1, 4, 6]])

In [65]:
np.random.randn(3,4)

array([[-1.78213296, -2.44607263,  0.3565718 ,  0.84363035],
       [ 0.02848247,  0.92029116, -0.27551979,  0.48681735],
       [ 0.49287301,  1.21810049,  1.38872111,  1.09348412]])

In [67]:
arr = np.random.randn(4,6)

In [68]:
import pandas as pd 
pd.DataFrame(arr)

0         1         2         3         4         5
0 -0.113523  0.226300 -0.970546 -0.875437 -1.091743 -1.222573
1 -0.770933 -1.127190 -0.573033  1.746680 -0.200071  0.862726
2  0.785964  0.421189 -0.250179 -0.509194  2.225231  1.126614
3 -0.202880 -0.047332 -0.061980  2.188364  1.078594  0.078281

In [69]:
np.random.rand(3,4)

array([[0.90304719, 0.05018297, 0.17852227, 0.57858984],
       [0.56989625, 0.87061387, 0.52262454, 0.5227468 ],
       [0.31950912, 0.64782878, 0.9038121 , 0.40149792]])

In [74]:
pd.DataFrame(np.random.randint(1,10,(500,500)))

0    1    2    3    4    5    6    7    8    9    ...  490  491  492  \
0      2    8    5    3    5    1    5    9    6    8  ...    3    9    3   
1      6    7    7    2    1    4    4    4    8    6  ...    6    1    8   
2      2    1    9    9    9    3    4    6    1    8  ...    2    8    7   
3      4    6    1    6    7    7    6    8    9    4  ...    2    7    7   
4      9    3    7    2    8    5    7    6    3    8  ...    6    5    9   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
495    1    1    2    7    8    9    3    6    7    5  ...    7    8    6   
496    2    9    8    7    6    8    7    1    3    6  ...    8    3    1   
497    3    3    6    6    7    9    7    9    2    9  ...    9    5    6   
498    6    7    8    1    1    3    6    3    8    8  ...    5    8    5   
499    9    2    2    1    7    2    8    4    5    7  ...    2    8    6   

     493  494  495  496  497  498  499  
0      9    6    3    9    6    1    5  
1      9    9    4    4    1    2    4  
2      9    2    9    9    8    2    4  
3      6    3    7    5    1    3    1  
4      4    9    3    8    7    4    5  
..   ...  ...  ...  ...  ...  ...  ...  
495    9    4    1    2    3    3    1  
496    2    8    1    1    1    5    5  
497    5    1    8    7    3    3    8  
498    5    8    3    4    1    8    5  
499    8    3    4    4    9    1    1  

[500 rows x 500 columns]

In [75]:
arr = np.random.rand(4,4)

In [76]:
arr.shape

(4, 4)

In [77]:
arr.reshape(8,2)

array([[0.77249546, 0.90185692],
       [0.6209876 , 0.53244867],
       [0.89490744, 0.55965993],
       [0.04698691, 0.35045069],
       [0.66001436, 0.13855861],
       [0.97389547, 0.19295127],
       [0.44774749, 0.25371566],
       [0.12764549, 0.5306592 ]])

In [79]:
arr1  = arr.reshape(-1,4)

In [80]:
arr1

array([[0.77249546, 0.90185692, 0.6209876 , 0.53244867],
       [0.89490744, 0.55965993, 0.04698691, 0.35045069],
       [0.66001436, 0.13855861, 0.97389547, 0.19295127],
       [0.44774749, 0.25371566, 0.12764549, 0.5306592 ]])

In [82]:
arr[0][3]

0.5324486678216076

In [85]:
arr[1:3,1:3]

array([[0.55965993, 0.04698691],
       [0.13855861, 0.97389547]])

In [87]:
arr =np.random.randint(1,100,(5,5))

In [89]:
arr[arr > 50]

array([92, 97, 89, 86, 83, 98, 93, 78, 75, 78, 95, 76, 59])

In [90]:
arr[arr<50]

array([42,  3,  6,  3, 11,  5, 20, 35, 24, 11, 17])

In [91]:
arr

array([[92, 97, 42,  3, 89],
       [ 6,  3, 11, 86, 83],
       [ 5, 98, 20, 93, 50],
       [78, 35, 75, 24, 78],
       [95, 76, 59, 11, 17]])

In [92]:
arr[2:4,1:3]

array([[98, 20],
       [35, 75]])

In [95]:
arr[0,0]=7098
arr

array([[7098,   97,   42,    3,   89],
       [   6,    3,   11,   86,   83],
       [   5,   98,   20,   93,   50],
       [  78,   35,   75,   24,   78],
       [  95,   76,   59,   11,   17]])

In [96]:
arr1 = np.random.randint(1,3,(3,3))

In [97]:
arr2 = np.random.randint(1,3,(3,3))

In [98]:
arr1 + arr2

array([[4, 2, 2],
       [2, 4, 3],
       [4, 2, 2]])

In [99]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [100]:
arr2 - arr1

array([[ 0,  0,  0],
       [ 0,  0, -1],
       [ 0,  0,  0]])

In [101]:
arr1 * arr2

array([[4, 1, 1],
       [1, 4, 2],
       [4, 1, 1]])

In [102]:
arr2/ arr1

array([[1. , 1. , 1. ],
       [1. , 1. , 0.5],
       [1. , 1. , 1. ]])

In [103]:
arr1 // arr2

array([[1, 1, 1],
       [1, 1, 2],
       [1, 1, 1]])

In [104]:
arr1 % arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [106]:
arr1 @ arr2

array([[7, 5, 4],
       [8, 7, 5],
       [7, 5, 4]])

In [107]:
arr1/0

C:\Users\HP\AppData\Local\Temp\ipykernel_13024\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [108]:
arr1  + 100

array([[102, 101, 101],
       [101, 102, 102],
       [102, 101, 101]])

In [109]:
arr1 

array([[2, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [110]:
arr1 ** 2

array([[4, 1, 1],
       [1, 4, 4],
       [4, 1, 1]])

In [112]:
# broadcasting in case of a numpy 
arr4 =np.zeros((4,4))

In [113]:
arr3 = np.array([1,2,3,4])

In [114]:
arr3

array([1, 2, 3, 4])

In [115]:
arr3 + arr4

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [120]:
arr3.transpose

<function ndarray.transpose>

In [121]:
arr3

array([1, 2, 3, 4])

In [122]:
arr3 = np.array([[1,2,3,4]])

In [123]:
arr3

array([[1, 2, 3, 4]])

In [129]:
arr = arr3 . T + arr4

In [130]:
arr3 + arr4

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [131]:
arr3

array([[1, 2, 3, 4]])

In [132]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [134]:
arr.mean

<function ndarray.mean>

In [135]:
arr.mean()

2.5

In [137]:
np.log10(arr)

array([[0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999]])

In [138]:
np.exp(arr)

array([[ 2.71828183,  2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  7.3890561 ],
       [20.08553692, 20.08553692, 20.08553692, 20.08553692],
       [54.59815003, 54.59815003, 54.59815003, 54.59815003]])

In [139]:
np.exp2(arr)

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.],
       [16., 16., 16., 16.]])

In [143]:
# Array manipulations
arr = np.random. randint(1,10,(3,4
                               
                               ))

In [145]:
arr

array([[8, 7, 4, 1],
       [7, 5, 7, 8],
       [4, 4, 5, 7]])

In [146]:
arr.reshape(6,2)

array([[8, 7],
       [4, 1],
       [7, 5],
       [7, 8],
       [4, 4],
       [5, 7]])

In [147]:
arr.T

array([[8, 7, 4],
       [7, 5, 4],
       [4, 7, 5],
       [1, 8, 7]])

In [148]:
arr

array([[8, 7, 4, 1],
       [7, 5, 7, 8],
       [4, 4, 5, 7]])

In [149]:
arr.flatten()

array([8, 7, 4, 1, 7, 5, 7, 8, 4, 4, 5, 7])

In [152]:
arr1 = np.array([1,2,3,4,5])

In [154]:
arr1

array([1, 2, 3, 4, 5])

In [155]:
arr1.ndim

1

In [157]:
np.expand_dims(arr1,axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [158]:
arr

array([[8, 7, 4, 1],
       [7, 5, 7, 8],
       [4, 4, 5, 7]])

In [159]:
np.squeeze(arr)

array([[8, 7, 4, 1],
       [7, 5, 7, 8],
       [4, 4, 5, 7]])

In [160]:
data = np.array([[1],[2],[3]])
print(data)
np.squeeze(data)

[[1]
 [2]
 [3]]


array([1, 2, 3])

In [161]:
arr1

array([1, 2, 3, 4, 5])

In [162]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [164]:
np.roll(arr1,shift=2)

array([4, 5, 1, 2, 3])

In [165]:
np.roll(arr,shift= 5)

array([[8, 4, 4, 5],
       [7, 8, 7, 4],
       [1, 7, 5, 7]])

In [166]:
arr

array([[8, 7, 4, 1],
       [7, 5, 7, 8],
       [4, 4, 5, 7]])

In [167]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [168]:
# Binary operation 
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))
print(arr1,arr2)

[[3 9 1 6]
 [1 8 5 7]
 [4 9 2 3]] [[6 9 3 9]
 [4 1 9 1]
 [3 8 4 1]]


In [169]:
arr1 + arr2

array([[ 9, 18,  4, 15],
       [ 5,  9, 14,  8],
       [ 7, 17,  6,  4]])

In [170]:
arr1 - arr2

array([[-3,  0, -2, -3],
       [-3,  7, -4,  6],
       [ 1,  1, -2,  2]])

In [172]:
arr1 ** arr2

array([[      729, 387420489,         1,  10077696],
       [        1,         8,   1953125,         7],
       [       64,  43046721,        16,         3]])

In [173]:
arr1 & arr2

array([[2, 9, 1, 0],
       [0, 0, 1, 1],
       [0, 8, 0, 1]])

In [174]:
arr1 | arr2

array([[ 7,  9,  3, 15],
       [ 5,  9, 13,  7],
       [ 7,  9,  6,  3]])

In [175]:
~arr1

array([[ -4, -10,  -2,  -7],
       [ -2,  -9,  -6,  -8],
       [ -5, -10,  -3,  -4]])

In [176]:
arr1 | arr2

array([[ 7,  9,  3, 15],
       [ 5,  9, 13,  7],
       [ 7,  9,  6,  3]])

In [178]:
arr1 [arr1 > arr2]

array([8, 7, 4, 9, 3])

In [179]:
# string function inside numpy 
str_arr = np.array(['syed','mansoor'])